### ISSUE TITLE
save stationary property getters

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pytram#21]
Implement access to stationary properties via getters in Estimator and derived classes.

**Comment by ppxasjsm** [comment]
hatten wir uns nicht dagegen entschieden?

**Comment by cwehmeyer** [comment]
pyfeat: ja
pytram: nein

**Comment by ppxasjsm** [comment]
ok, damit können dann die wrappers in pyfeat auf die info in the pytram objekten zugreifen

**Comment by cwehmeyer** [comment]
ja. jeder pytram estimator verfügt sicher über die getter
- pi_i
- pi_K_i
- f_K
- f_K_i
- f_i
- n_therm_states
- n_markov_states
- C_K_ij

**Comment by ppxasjsm** [comment]
ok perfekt
