### ISSUE TITLE
negative transition matrix entries

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pytram#26]
A number of times now I have observed that the calculation of diagonal elements (1.0-row_sum)  in a transition matrix estimation can yield small (absolute value is usually < 10^{-10}) negative values as the sum over the non-diagonal elements in the particular row approaches 1.

Any ideas how to handle this in the general case?

**Comment by franknoe** [comment]
This should only occur for c_ii = 0. Is this the case?

I would suggest to enforce bounds [0,1] and subsequently divide by the row sum
