### ISSUE TITLE
conda build

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pytram#34]
Make pytram compatible with conda.

**Comment by cwehmeyer** [comment]
Added conda-recipe to the repository

**Comment by franknoe** [comment]
nice

-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------
