### ISSUE TITLE
pylint does not like pytram

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/pytram#37]
Here is the summary report from pylint:

Messages
--------

+-------------------------------+------------+
|message id                     |occurrences |
+===============================+============+
|bad-whitespace                 |596         |
+-------------------------------+------------+
|invalid-name                   |150         |
+-------------------------------+------------+
|no-member                      |98          |
+-------------------------------+------------+
|missing-docstring              |44          |
+-------------------------------+------------+
|line-too-long                  |42          |
+-------------------------------+------------+
|bad-continuation               |23          |
+-------------------------------+------------+
|trailing-whitespace            |18          |
+-------------------------------+------------+
|no-name-in-module              |7           |
+-------------------------------+------------+
|too-many-arguments             |6           |
+-------------------------------+------------+
|bad-indentation                |6           |
+-------------------------------+------------+
|unused-variable                |4           |
+-------------------------------+------------+
|no-self-use                    |4           |
+-------------------------------+------------+
|too-many-instance-attributes   |3           |
+-------------------------------+------------+
|unused-argument                |2           |
+-------------------------------+------------+
|super-init-not-called          |2           |
+-------------------------------+------------+
|lost-exception                 |2           |
+-------------------------------+------------+
|duplicate-code                 |2           |
+-------------------------------+------------+
|too-many-locals                |1           |
+-------------------------------+------------+
|fixme                          |1           |
+-------------------------------+------------+
|cyclic-import                  |1           |
+-------------------------------+------------+
|attribute-defined-outside-init |1           |
+-------------------------------+------------+

Global evaluation
-----------------
Your code has been rated at -13.30/10

I think the 'bad whitespaces' are the name( var ) notation. Docstring and line lengths I can try and fix.

**Comment by franknoe** [comment]
For many of the reports you have to check if they are real. What is 
behind the "no-member" for example? Are they really no members or is 
pylint for some reason a wrong version, or simply doesn't know that in a 
A.shape, A is an array, because it just can't know it?
In the latter case you could always use np.shape(A), which would be more 
safe anyway, because that also works for lists.

Am 09/04/15 um 08:47 schrieb ppxasjsm:
>
> Here is the summary report from pylint:
>
>
>     Messages
>
> +-------------------------------+------------+
> |message id |occurrences |
> +===============================+============+
> |bad-whitespace |596 |
> +-------------------------------+------------+
> |invalid-name |150 |
> +-------------------------------+------------+
> |no-member |98 |
> +-------------------------------+------------+
> |missing-docstring |44 |
> +-------------------------------+------------+
> |line-too-long |42 |
> +-------------------------------+------------+
> |bad-continuation |23 |
> +-------------------------------+------------+
> |trailing-whitespace |18 |
> +-------------------------------+------------+
> |no-name-in-module |7 |
> +-------------------------------+------------+
> |too-many-arguments |6 |
> +-------------------------------+------------+
> |bad-indentation |6 |
> +-------------------------------+------------+
> |unused-variable |4 |
> +-------------------------------+------------+
> |no-self-use |4 |
> +-------------------------------+------------+
> |too-many-instance-attributes |3 |
> +-------------------------------+------------+
> |unused-argument |2 |
> +-------------------------------+------------+
> |super-init-not-called |2 |
> +-------------------------------+------------+
> |lost-exception |2 |
> +-------------------------------+------------+
> |duplicate-code |2 |
> +-------------------------------+------------+
> |too-many-locals |1 |
> +-------------------------------+------------+
> |fixme |1 |
> +-------------------------------+------------+
> |cyclic-import |1 |
> +-------------------------------+------------+
> |attribute-defined-outside-init |1 |
> +-------------------------------+------------+
>
>
>     Global evaluation
>
> Your code has been rated at -13.30/10
>
> I think the 'bad whitespaces' are the name( var ) notation. Docstring 
> and line lengths I can try and fix.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/pytram/issues/37>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by cwehmeyer** [comment]
So far, the no-member reports are not real: they appear in contexts like of `dtype=np.float64`, `dtype=np.intc`, and `from numpy import get_include`. The huge amount of bad white space/indention/continuation is due to my coding style.

**Comment by cwehmeyer** [comment]
The `no-member` errors with numpy are a known issue with pylint. The recommendation is to simply ignore these errors or disable this particular error type.

**Comment by ppxasjsm** [comment]
Ok, I guess since we are aware of this and we are slowly improving this, I'll close this issue
