### ISSUE TITLE
xTRAM_examples broken in release 0.2.2

### ISSUE THREAD

**Issue by ppxasjsm** [markovmodel/pytram#42]
I think somehow the update of the signs on f_i has broken xTRAM. Have a look at the output of the xTRAM examples. 
![xtram_broken](https://cloud.githubusercontent.com/assets/3668316/8191156/7b1adf72-145e-11e5-8b7b-84416b753a7c.png)

**Comment by franknoe** [comment]
It would be good to execute examples in the automatic tests. I think 
@marscher has suggested a way to do this.

Am 16/06/15 um 20:33 schrieb ppxasjsm:
>
> I think somehow the update of the signs on f_i has broken xTRAM. Have 
> a look at the output of the xTRAM examples.
> xtram_broken 
> <https://cloud.githubusercontent.com/assets/3668316/8191156/7b1adf72-145e-11e5-8b7b-84416b753a7c.png>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/pytram/issues/42>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by ppxasjsm** [comment]
Ok I'll look into this.

**Comment by cwehmeyer** [comment]
The sign change was in f_K; the f_i remain unchanged.

**Comment by ppxasjsm** [comment]
Fixed
