### ISSUE TITLE
name space clash

### ISSUE THREAD

**Issue by cwehmeyer** [markovmodel/pytram#43]
We need to rename (or relocate) either the estimators`s submodules or the API functions, because
```python
from pytram import dtram
```
results in importing the dram module instead of the API function.

**Comment by ppxasjsm** [comment]
Ah! That would explain some strange behaviour I have seen.

**Comment by franknoe** [comment]
I haven't looked into this, but if I understand your problem correctly, 
you can rename the module name that the dtram function is in without 
affecting the user behavior. For example if you have a dtram.py and 
rename that to dtram_xx.py you can still do a
     from dtram_xx import dtram
in pytram.__init__, and you can still do the import statement below.

Am 24/06/15 um 13:58 schrieb Christoph Wehmeyer:
>
> We need to rename (or relocate) either the estimators`s submodules or 
> the API functions, because
>
> from  pytramimport  dtram
>
> results in importing the dram module instead of the API function.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/markovmodel/pytram/issues/43>.
>


-- 

----------------------------------------------
Prof. Dr. Frank Noe
Head of Computational Molecular Biology group
Freie Universitaet Berlin

Phone: (+49) (0)30 838 75354
Web:   research.franknoe.de
Mail:  Arnimallee 6, 14195 Berlin, Germany
----------------------------------------------

**Comment by cwehmeyer** [comment]
Yes, that is exactly what I have in mind.

**Comment by cwehmeyer** [comment]
fixed:
```
pytram/dtram -> pytram/_dtram
pytram/xtram -> pytram/_xtram
```
